(() => {
  "use strict";
  const esc = value => String(value ?? "").replace(/[&<>"']/g, char => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#39;" }[char]));
  const labels = lang => lang === "zh-TW" ? {
    title:"臨時出庫／送貨單", customer:"客戶／收貨地點", requester:"申請人", dispatch:"出庫日期", delivery:"送貨日期", number:"送貨單號", product:"商品名稱", code:"商品編號", qty:"數量", use:"用途", returns:"歸還", note:"備註", yes:"須歸還", no:"不須歸還", original:"正本", copy:"副本", released:"出庫人員", delivered:"送貨人員", received:"收貨人簽名", date:"日期", draft:"草稿 — 待審核", reference:"INV／參考編號"
  } : lang === "en" ? {
    title:"TEMPORARY DELIVERY NOTE", customer:"Customer / delivery location", requester:"Requested by", dispatch:"Dispatch date", delivery:"Delivery date", number:"Document no.", product:"Product", code:"Product code", qty:"Quantity", use:"Purpose", returns:"Return", note:"Notes", yes:"Yes", no:"No", original:"ORIGINAL", copy:"COPY", released:"Released by", delivered:"Delivered by", received:"Received by", date:"Date", draft:"DRAFT — PENDING APPROVAL", reference:"INV / reference"
  } : {
    title:"ใบนำสินค้าออกจากคลัง / ใบส่งของชั่วคราว", customer:"ชื่อลูกค้า / สถานที่รับสินค้า", requester:"ผู้ยื่นคำร้อง", dispatch:"วันที่นำของออก", delivery:"วันที่ส่งของ", number:"เลขที่ใบส่งของ", product:"ชื่อสินค้า", code:"รหัสสินค้า", qty:"จำนวน", use:"ใช้งาน", returns:"กลับคืน", note:"หมายเหตุ", yes:"คืน", no:"ไม่คืน", original:"ต้นฉบับ", copy:"สำเนา", released:"ผู้นำของออก", delivered:"ผู้ส่งของ", received:"ลายเซ็นผู้รับของ", date:"วันที่", draft:"ฉบับร่าง — รออนุมัติ", reference:"INV / เอกสาร"
  };

  function buildParts({ request, lines, itemById, staffNames, purposeNames, lang="th", formatNumber, formatDate }) {
    const label=labels(lang), approved=request.status === "approved", draft=!approved;
    const fmt=formatNumber || (n => String(n ?? "–"));
    const date=formatDate || (n => String(n ?? "–"));
    const pageSize=10;
    const chunks=[];
    for(let start=0;start<Math.max(lines.length,1);start+=pageSize) chunks.push(lines.slice(start,start+pageSize));
    const page = (copy,chunk,pageIndex) => {
      const rows=Array.from({length:pageSize},(_,rowIndex)=>{
        const line=chunk[rowIndex], number=pageIndex*pageSize+rowIndex+1;
        if(!line) return `<tr class="item-row blank-row"><td>${number}</td><td></td><td></td><td></td><td></td><td></td><td></td></tr>`;
        const item=itemById(line.item_id);
        return `<tr class="item-row"><td>${number}</td><td>${esc([item?.code||line.code,item?.model||line.model].filter(Boolean).join(" / "))}</td><td>${esc(item?.spec||item?.model||line.model||"–")}</td><td>${fmt(approved ? line.approved_qty : line.requested_qty)}</td><td>${esc(purposeNames[line.purpose]||purposeNames.sale)}</td><td>${line.return_required?label.yes:label.no}</td><td>${esc(line.line_note||"")}</td></tr>`;
      }).join("");
      const pageNumber=chunks.length>1 ? ` · ${pageIndex+1}/${chunks.length}` : "";
      return `<section class="delivery-page">${draft ? `<div class="draft-mark">${label.draft}</div>` : ""}<header><div class="company"><b>LASTER TECH (THAILAND) CO., LTD.</b><small>Temporary warehouse dispatch document</small></div><div class="brand">LASTER TECH</div></header><h1>${label.title}</h1><div class="doc-meta"><div><b>${label.customer}</b><span>${esc(request.customer||"–")}</span></div><div><b>${label.requester}</b><span>${esc(staffNames[request.requester_id]||"–")}</span></div><div><b>${label.dispatch}</b><span>${esc(date(request.document_date))}</span></div><div><b>${label.delivery}</b><span>${esc(date(request.delivery_date||request.document_date))}</span></div><div><b>${label.number}</b><span>${esc(request.delivery_note_no||String(request.id).slice(0,8))}</span></div><div><b>${label.reference}</b><span>${esc(request.doc_no||"–")}</span></div></div><div class="copy-label">${copy}${pageNumber}</div><table><thead><tr><th>#</th><th>${label.code}</th><th>${label.product}</th><th>${label.qty}</th><th>${label.use}</th><th>${label.returns}</th><th>${label.note}</th></tr></thead><tbody>${rows}</tbody></table>${request.note?`<p class="document-note"><b>${label.note}:</b> ${esc(request.note)}</p>`:""}<footer>${[label.released,label.delivered,label.received].map(value=>`<div><span>( ______________________________ )</span><b>${value}</b><small>${label.date}: ____________________</small></div>`).join("")}</footer></section>`;
    };
    const pages=[...chunks.map((chunk,index)=>page(label.original,chunk,index)),...chunks.map((chunk,index)=>page(label.copy,chunk,index))].join("");
    const css=`@page{size:A4 landscape;margin:8mm}.sweeo-dn,.sweeo-dn *{box-sizing:border-box}.sweeo-dn{font-family:'IBM Plex Sans Thai','PingFang TC','Microsoft JhengHei','Noto Sans TC',Arial,sans-serif;color:#111}.sweeo-dn .delivery-page{height:190mm;position:relative;page-break-after:always;padding:2mm 2mm 32mm}.sweeo-dn .delivery-page:last-child{page-break-after:auto}.sweeo-dn header{display:flex;justify-content:space-between;align-items:center}.sweeo-dn .company b,.sweeo-dn .company small{display:block}.sweeo-dn .company b,.sweeo-dn .brand{color:#174b91}.sweeo-dn .brand{font-size:24px;font-weight:700}.sweeo-dn .delivery-page h1{text-align:center;font-size:19px;margin:2mm 0}.sweeo-dn .doc-meta{display:grid;grid-template-columns:1fr 1fr 1fr;border:1px solid #555}.sweeo-dn .doc-meta div{display:flex;gap:6px;padding:4px 7px;border-right:1px solid #777;border-bottom:1px solid #777;font-size:11px}.sweeo-dn .doc-meta div:nth-child(3n){border-right:0}.sweeo-dn .doc-meta div:nth-last-child(-n+3){border-bottom:0}.sweeo-dn .doc-meta b{white-space:nowrap}.sweeo-dn .copy-label{position:absolute;right:4mm;top:17mm;font-weight:700}.sweeo-dn table{width:100%;table-layout:fixed;border-collapse:collapse;margin-top:4mm;font-size:10px}.sweeo-dn th,.sweeo-dn td{border:1px solid #777;padding:3px 4px;text-align:left;height:8.5mm;overflow:hidden}.sweeo-dn th{height:8mm;background:#ddd;text-align:center}.sweeo-dn th:nth-child(1){width:5%}.sweeo-dn th:nth-child(2){width:20%}.sweeo-dn th:nth-child(3){width:30%}.sweeo-dn th:nth-child(4){width:8%}.sweeo-dn th:nth-child(5){width:12%}.sweeo-dn th:nth-child(6){width:9%}.sweeo-dn th:nth-child(7){width:16%}.sweeo-dn th:nth-child(1),.sweeo-dn td:nth-child(1),.sweeo-dn th:nth-child(4),.sweeo-dn td:nth-child(4),.sweeo-dn th:nth-child(6),.sweeo-dn td:nth-child(6){text-align:center}.sweeo-dn .blank-row td{color:#777}.sweeo-dn .document-note{font-size:10px;margin:2mm 0;max-height:12mm;overflow:hidden}.sweeo-dn footer{position:absolute;left:2mm;right:2mm;bottom:2mm;display:grid;grid-template-columns:repeat(3,1fr);gap:25mm;text-align:center;font-size:10px}.sweeo-dn footer span,.sweeo-dn footer b,.sweeo-dn footer small{display:block;margin-top:2mm}.sweeo-dn .draft-mark{position:absolute;transform:rotate(-25deg);font-size:40px;color:rgba(190,40,40,.16);font-weight:700;left:30%;top:45%;z-index:2}@media screen{.sweeo-dn{background:#ddd;padding:10px;min-width:max-content}.sweeo-dn .delivery-page{width:277mm;margin:0 auto 10px;background:#fff;box-shadow:0 2px 12px #777}}`;
    return { css, html:`<div class="sweeo-dn" lang="${esc(lang)}">${pages}</div>`, title:request.delivery_note_no||label.title };
  }
  function buildDocument(options) {
    const parts=buildParts(options);
    return `<!doctype html><html lang="${esc(options.lang||"th")}"><head><meta charset="utf-8"><title>${esc(parts.title)}</title><link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Thai:wght@400;500;600;700&display=swap" rel="stylesheet"><style>${parts.css}</style></head><body>${parts.html}</body></html>`;
  }
  window.SWEEO_DELIVERY = { buildParts, buildDocument };
})();
